// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKbLnSo-YtSjXHugdC7GPOam3LoSTe_c',
    appId: '1:29106224869:web:3c5fea36c0ea387759de0c',
    messagingSenderId: '29106224869',
    projectId: 'notes-flutter-mynotes',
    authDomain: 'notes-flutter-mynotes.firebaseapp.com',
    storageBucket: 'notes-flutter-mynotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDdGGRcs3VUr2Mw-zFigyy74AnJ5Hm4QU',
    appId: '1:29106224869:android:c85e5cb0f3890fb959de0c',
    messagingSenderId: '29106224869',
    projectId: 'notes-flutter-mynotes',
    storageBucket: 'notes-flutter-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn0zpfF7xvSuTv1ZgGc_882xiu35gXbWg',
    appId: '1:29106224869:ios:14d45280a157f72159de0c',
    messagingSenderId: '29106224869',
    projectId: 'notes-flutter-mynotes',
    storageBucket: 'notes-flutter-mynotes.appspot.com',
    iosClientId: '29106224869-3dscnt2oo2afjovf7lo5hgngn94q80sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
